In [ ]:

class mainWindow(QMainWindow):
    buttonClickedSignal = Signal()
    timerResetSignal = Signal()
    gameOverSignal = Signal()
    computerMoveSignal = Signal(dict)
    timeElapsedSignal = Signal(int)

    def __init__(self):
        super().__init__()
        self.status = gameStatus.IN_PROGRESS
        self.cellWidth = 80
        self.playerAction = 0
        self.player = CurrentPlayer.HUMAN
        self.pieceSelector = pieceSelector(self)
        self.board = Connect4Board(self, self.cellWidth)
        self.alphazero = AlphaZero(self)
        self.timerGUI = TimerWidget(self, self.cellWidth)
        self.timer = Timer(self)
        self.gameInfo = gameInfoWidget(self)
        self.initUI()

    def initUI(self):
        self.setWindowTitle("Connect-Four")
        self.setGeometry(0, 0, 10.5*self.cellWidth, 7.5*self.cellWidth)

        self.board.setGeometry(0, 0, 7.5*self.cellWidth, 7.5*self.cellWidth)
        self.timerGUI.setGeometry(7.5*self.cellWidth, 0, 3*self.cellWidth, 3*self.cellWidth)
        self.gameInfo.setGeometry(7.5*self.cellWidth, 3.5*self.cellWidth, 3*self.cellWidth, 5*self.cellWidth)
        self.pieceSelector.setGeometry(0, 0, 10.5*self.cellWidth, 7.5*self.cellWidth)

        self.board.show()
        self.timerGUI.show()
        self.gameInfo.show()
        self.pieceSelector.show()

        self.setFixedSize(self.size())

        self.show()

    def paintEvent(self, event):
        qp = QPainter(self)
        if not qp.isActive():
            qp.begin(self)
        qp.fillRect(self.rect(), QBrush(QColor(0, 0, 0)))
        qp.end()

    def switchPlayer(self):
        if self.player == CurrentPlayer.COMPUTER:
            self.player = CurrentPlayer.HUMAN
        else:
            self.player = CurrentPlayer.COMPUTER

In [1]:
if -1:
    print("True")

True


In [7]:
from enum import Enum
class CurrentPlayer(Enum):
    HUMAN = 1
    NONE = 0
    COMPUTER = -1
cp = CurrentPlayer.NONE
print(CurrentPlayer(1))
print(cp.value)
print(cp)
cp = cp(1)

CurrentPlayer.HUMAN
0
CurrentPlayer.NONE


TypeError: 'CurrentPlayer' object is not callable

In [5]:
import numpy as np
a = np.zeros([6,7])
print(a)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [6]:
np.array([[0 for _ in range(7)] for _ in range(6)])

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [6]:
from copy import copy
a = 1
b = 1
a = b
b = 2
a = 3
b

2

In [13]:
a = [1,2]
b = copy(a)
a[0] = 5
print(copy(b))

[1, 2]


In [8]:
2**30

1073741824

In [9]:
2**23

8388608

In [11]:
2**17

131072

In [13]:
2**10

1024

In [14]:
2**9

512

In [1]:
from PySide6.QtGui import QPainter
from PySide6.QtWidgets import QWidget, QApplication, QPushButton, QMainWindow
import functools

class mainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setGeometry(
            0,
            0,
            100,
            100
        )
        self.playAgainButton = QPushButton("Play Again", self)
        self.playAgainButton.clicked.connect(functools.partial(self.disablePlayAgainButton))
        self.playAgainButton.setGeometry(
            7.5*80,
            (3.5+0.25)*80,
            2*80,
            0.25*80
        )
        self.show()
    def disablePlayAgainButton(self):
        self.playAgainButton.setEnabled(True)

if __name__ == '__main__':
    app = QApplication.instance()
    mainWin = mainWindow()
    app.exec()

: 

In [ ]:
d = dict()


# 4-in-a-row  
Connect-4 game implemented using Python-PySide6 and with an AI agent inspired by DeepMind's AlphaZero algorithm.
  
These are some screenshots of the game:  
![human-win scenario](Game_screenshot_1.png)
![first screen](Game_screenshot_2.png)

In [1]:
import sys
from PySide6.QtWidgets import (
    QApplication, QGraphicsScene, QGraphicsView, QGraphicsPixmapItem, QGraphicsBlurEffect
)
from PySide6.QtGui import QPixmap


# Step 1: Create the application
app = QApplication(sys.argv)

# Step 2: Create a scene and a view
scene = QGraphicsScene()
view = QGraphicsView(scene)

# Step 3: Load an image and add it to the scene
pixmap_item = QGraphicsPixmapItem(QPixmap("example_image.png"))
scene.addItem(pixmap_item)

# Step 4: Create a blur effect
blur_effect = QGraphicsBlurEffect()
blur_effect.setBlurRadius(10)  # Set the blur radius

# Step 5: Apply the blur effect to the item
pixmap_item.setGraphicsEffect(blur_effect)

# Step 6: Show the view
view.show()

# Step 7: Run the application loop
sys.exit(app.exec())


SystemExit: 0

c:\Users\nagar\AppData\Local\Programs\Python\Python312\Lib\site-packages\IPython\core\interactiveshell.py:3585: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [1]:
import sys
from PySide6.QtWidgets import (
    QApplication, QWidget, QVBoxLayout, QHBoxLayout, QPushButton, QGraphicsBlurEffect, QGraphicsOpacityEffect
)
from PySide6.QtCore import Qt

class MainWindow(QWidget):
    def __init__(self):
        super().__init__()

        # Main layout
        main_layout = QVBoxLayout()
        self.setLayout(main_layout)

        # Lower widgets (side-to-side)
        lower_layout = QHBoxLayout()
        main_layout.addLayout(lower_layout)

        # Add widgets to the lower section
        self.widgets = []
        for i in range(3):
            button = QPushButton(f"Widget {i+1}")
            self.widgets.append(button)
            lower_layout.addWidget(button)

        # Apply blur effects to lower widgets
        for widget in self.widgets:
            blur_effect = QGraphicsBlurEffect()
            blur_effect.setBlurRadius(10)  # Set blur radius
            widget.setGraphicsEffect(blur_effect)

        # Top overlay widget
        self.overlay_widget = QPushButton("Overlay Widget")
        self.overlay_widget.setFixedHeight(100)  # Example fixed size for overlay
        self.overlay_widget.setStyleSheet(
            "background-color: rgba(255, 255, 255, 200); border: 1px solid black;"
        )  # Semi-transparent white background

        # Apply opacity effect to the overlay
        opacity_effect = QGraphicsOpacityEffect()
        opacity_effect.setOpacity(0.9)  # Set the opacity level (0: fully transparent, 1: fully opaque)
        self.overlay_widget.setGraphicsEffect(opacity_effect)

        # Add overlay widget to main layout
        main_layout.addWidget(self.overlay_widget, alignment=Qt.AlignTop)

        # Styling the main window
        self.setStyleSheet("background-color: lightgray;")  # Example background color
        self.resize(400, 300)  # Resize main window


# Run the application
app = QApplication(sys.argv)
window = MainWindow()
window.show()
sys.exit(app.exec())


SystemExit: 0

c:\Users\nagar\AppData\Local\Programs\Python\Python312\Lib\site-packages\IPython\core\interactiveshell.py:3585: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [1]:
f = True
g = not f
print(g)

False
